### ISSUE TITLE
Forgematica doesn't recognise the forge Port of the Libary Mod on 1.19.4

### ISSUE THREAD

**Issue by MyrddinN** [ThinkingStudios/Litematica-Forge#36]
[crash-2023-12-01_17.01.40-fml.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/13529661/crash-2023-12-01_17.01.40-fml.txt)

**Comment by MyrddinN** [comment]
it works with the previous version 0.1.8 but not with the newest version 0.1.9

**Comment by TexBlock** [comment]
This has been fixed in the version just released.

**Comment by MyrddinN** [comment]
[crash-2024-01-28_12.52.02-fml.txt](https://github.com/ThinkingStudios/Litematica-Forge/files/14075883/crash-2024-01-28_12.52.02-fml.txt)

I tried with with the newest version (0.1.11) the error is still there

**Comment by MyrddinN** [comment]
oh with the newest beta of forgematica and the newest maFgLib the error is gone, thanks for the work in porting these mods :D
